services:
  backend:
    build:
      context: .
      dockerfile: chatbot_backend/Dockerfile
    container_name: agronova_backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agronova_db
    volumes:
      - ./chatbot_backend:/app
    depends_on:
      - frontend
      - db

  frontend:
    build:
      context: .
      dockerfile: project/Dockerfile
    container_name: agronova_frontend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agronova_db
    volumes:
      - ./project:/app
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: florasight
      POSTGRES_PASSWORD: florasight  # Must exactly match Django settings
      POSTGRES_DB: florasight_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
